[package]
name = "servcat-server"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "servcat-server"
path = "src/main.rs"

[dependencies]
servcat-model.workspace = true
servcat-db.workspace = true
servcat-connectors.workspace = true
servcat-workflow-engine.workspace = true
servcat-approvals.workspace = true

axum.workspace = true
axum-extra = { version = "0.10", features = ["typed-header", "cookie"] }
askama = "0.12"
tokio = { workspace = true, features = ["time", "net", "fs"] }
tower.workspace = true
tower-http.workspace = true
url.workspace = true
base64.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
dotenvy.workspace = true
jsonwebtoken.workspace = true
argon2.workspace = true
rand.workspace = true
sha2 = "0.10"
hex = "0.4"
sqlx.workspace = true
async-trait.workspace = true
time = "0.3"
